project_id = "utrotueaxpydwiygkqgn"

[functions.stripe-webhook]
verify_jwt = false

[functions.signup-user]
verify_jwt = false

[functions.send-login-code]
verify_jwt = false

[functions.verify-login-code]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.manage-org-members]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.get-client-ip]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false