project_id = "utrotueaxpydwiygkqgn"

[functions.stripe-webhook]
verify_jwt = false

[functions.signup-user]
verify_jwt = false

[functions.send-login-code]
verify_jwt = false

[functions.verify-login-code]
verify_jwt = false